<a href="https://colab.research.google.com/github/fentahunb/vgc2023-shortcourse-4d/blob/main/MyFirestMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**## This is my firest machine learning **

#: **My first machine learning programme**
link of the tutoreal video can be found
https://youtu.be/29ZQ3TDGgRQ

#**load data**

###connect google drive data with google collab

In [ ]:
from google.colab import drive # used to import drive module from google cplab packages
drive.mount("\content\drive") # used to connect google drive to the colab

In [7]:
import pandas as pd
url1 = "https://drive.google.com/file/d/1ClVidXIRtsoQTfdGL5e9v5UeHjH0vo5-/view?usp=sharing"
url2 = "https://raw.githubusercontent.com/timothypesi/Data-Sets-For-Machine-Learning-/main/california_housing_train.csv"
df = pd.read_csv(url2)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]


#**Data Preparation**

In [8]:
x = df["median_house_value"] # selet the colomn of  median_house_value
x

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [11]:
y = df.drop("median_house_value",axis =1) # selet all except the colomn of  median_house_value
y

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

###*split the data as training and testing sets*

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2, random_state= 100)


In [35]:
x_train

14730    101400.0
9389      58000.0
7662     256300.0
9146      56500.0
13485    143500.0
           ...   
16304    349200.0
79        69400.0
12119     55900.0
14147    232500.0
5640     206300.0
Name: median_house_value, Length: 13600, dtype: float64

In [33]:
y_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14730    -122.19     37.77                45.0       1852.0           393.0   
9389     -119.21     36.38                18.0       2158.0           413.0   
7662     -118.37     33.90                32.0        332.0           103.0   
9146     -119.02     35.34                35.0       1650.0           390.0   
13485    -121.96     38.34                14.0       3035.0           680.0   
...          ...       ...                 ...          ...             ...   
16304    -122.50     37.92                32.0       2639.0           415.0   
79       -115.56     32.80                15.0       1171.0           328.0   
12119    -121.44     38.63                33.0       1077.0           271.0   
14147    -122.07     37.70                39.0       1420.0           272.0   
5640     -118.18     33.98                40.0       1698.0           431.0   

       population  households  median_income  
14730      1132.0       349.0         2.7159  
9389       1461.0       395.0         2.0216  
7662        177.0       102.0         3.3409  
9146       1145.0       343.0         1.5357  
13485      1597.0       663.0         3.6036  
...           ...         ...            ...  
16304      1013.0       408.0         6.1632  
79         1024.0       298.0         1.3882  
12119       753.0       236.0         1.3462  
14147       645.0       277.0         4.1250  
5640       1280.0       405.0         2.6250  

[13600 rows x 8 columns]

In [32]:
x_test

1559     500001.0
5775     113600.0
10247    107200.0
5234     201000.0
1416     198500.0
           ...   
9213      64600.0
15348    218200.0
14256     65500.0
5688     152500.0
6548     162100.0
Name: median_house_value, Length: 3400, dtype: float64

In [31]:
y_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1559     -117.22     33.87                16.0         56.0             7.0   
5775     -118.19     33.89                38.0       4018.0           986.0   
10247    -119.97     38.93                24.0        856.0           185.0   
5234     -118.14     34.19                45.0       3595.0           619.0   
1416     -117.18     32.80                30.0       2456.0           390.0   
...          ...       ...                 ...          ...             ...   
9213     -119.06     36.07                20.0       2683.0           553.0   
15348    -122.29     37.89                52.0       3171.0           698.0   
14256    -122.09     39.13                28.0       4169.0           895.0   
5688     -118.18     33.78                20.0       1852.0           556.0   
6548     -118.28     34.25                29.0       2559.0           787.0   

       population  households  median_income  
1559         39.0        14.0         2.6250  
5775       3702.0       927.0         2.9293  
10247       388.0       108.0         3.1806  
5234       1686.0       607.0         4.7300  
1416       1022.0       393.0         3.8542  
...           ...         ...            ...  
9213       1497.0       548.0         1.7031  
15348      1498.0       696.0         3.1795  
14256      2587.0       810.0         2.3310  
5688       1712.0       556.0         1.4565  
6548       1886.0       769.0         2.6036  

[3400 rows x 8 columns]

#train the model**

## *Linear Regression*

In [36]:
from sklearn.linear_model import LinearRegression
x_train = x_train.values.reshape(-1, 1)
x_test = x_test.values.reshape(-1, 1)
lr = LinearRegression()
lr.fit(x_train, y_train)


LinearRegression()

## apply the model for pridiction

In [37]:
y_lr_train_prid =lr.predict(x_train)
y_lr_test_prid =lr.predict(x_test)


In [38]:
print(y_lr_train_prid,y_lr_test_prid)

[[-119.50698949   35.93500158   27.42393489 ... 1444.40768241
   475.08528222    2.66818713]
 [-119.48078979   36.05820488   26.93804457 ... 1454.10239376
   465.41415088    2.17099208]
 [-119.60049948   35.49527371   29.1581379  ... 1409.80605135
   509.60275329    4.44273815]
 ...
 [-119.47952206   36.06416633   26.91453375 ... 1454.5714927
   464.94619291    2.14693425]
 [-119.5861319    35.5628368    28.89168192 ... 1415.12250596
   504.29922965    4.1700828 ]
 [-119.57031549   35.63721298   28.59835642 ... 1420.97507364
   498.46089691    3.86993278]] [[-119.74761683   34.80345884   31.886524   ... 1355.36801332
   563.90838412    7.23460294]
 [-119.51435438   35.9003684    27.56052157 ... 1441.68244097
   477.80389518    2.80795164]
 [-119.51049083   35.91853663   27.48886954 ... 1443.11207583
   476.37773756    2.73463256]
 ...
 [-119.48531739   36.03691398   27.02201179 ... 1452.42704042
   467.08542934    2.25691288]
 [-119.53783752   35.78993964   27.99603156 ... 1432.9929416

In [39]:
y_lr_train_prid =lr.predict(x_train)
y_lr_test_prid =lr.predict(x_test)


In [40]:
print(y_lr_train_prid, y_lr_test_prid)

[[-119.50698949   35.93500158   27.42393489 ... 1444.40768241
   475.08528222    2.66818713]
 [-119.48078979   36.05820488   26.93804457 ... 1454.10239376
   465.41415088    2.17099208]
 [-119.60049948   35.49527371   29.1581379  ... 1409.80605135
   509.60275329    4.44273815]
 ...
 [-119.47952206   36.06416633   26.91453375 ... 1454.5714927
   464.94619291    2.14693425]
 [-119.5861319    35.5628368    28.89168192 ... 1415.12250596
   504.29922965    4.1700828 ]
 [-119.57031549   35.63721298   28.59835642 ... 1420.97507364
   498.46089691    3.86993278]] [[-119.74761683   34.80345884   31.886524   ... 1355.36801332
   563.90838412    7.23460294]
 [-119.51435438   35.9003684    27.56052157 ... 1441.68244097
   477.80389518    2.80795164]
 [-119.51049083   35.91853663   27.48886954 ... 1443.11207583
   476.37773756    2.73463256]
 ...
 [-119.48531739   36.03691398   27.02201179 ... 1452.42704042
   467.08542934    2.25691288]
 [-119.53783752   35.78993964   27.99603156 ... 1432.9929416

In [41]:
y_lr_train_prid

array([[-119.50698949,   35.93500158,   27.42393489, ..., 1444.40768241,
         475.08528222,    2.66818713],
       [-119.48078979,   36.05820488,   26.93804457, ..., 1454.10239376,
         465.41415088,    2.17099208],
       [-119.60049948,   35.49527371,   29.1581379 , ..., 1409.80605135,
         509.60275329,    4.44273815],
       ...,
       [-119.47952206,   36.06416633,   26.91453375, ..., 1454.5714927 ,
         464.94619291,    2.14693425],
       [-119.5861319 ,   35.5628368 ,   28.89168192, ..., 1415.12250596,
         504.29922965,    4.1700828 ],
       [-119.57031549,   35.63721298,   28.59835642, ..., 1420.97507364,
         498.46089691,    3.86993278]])

In [42]:
y_lr_test_prid

array([[-119.74761683,   34.80345884,   31.886524  , ..., 1355.36801332,
         563.90838412,    7.23460294],
       [-119.51435438,   35.9003684 ,   27.56052157, ..., 1441.68244097,
         477.80389518,    2.80795164],
       [-119.51049083,   35.91853663,   27.48886954, ..., 1443.11207583,
         476.37773756,    2.73463256],
       ...,
       [-119.48531739,   36.03691398,   27.02201179, ..., 1452.42704042,
         467.08542934,    2.25691288],
       [-119.53783752,   35.78993964,   27.99603156, ..., 1432.99294163,
         486.47225944,    3.25359421],
       [-119.54363285,   35.7626873 ,   28.1035096 , ..., 1430.84848935,
         488.61149587,    3.36357284]])

#**model performance**
compare the y raining data with its pridicted values to check the model performance

In [50]:
from sklearn.metrics import mean_squared_error,r2_score
lr_train_mse = mean_squared_error(y_train, y_lr_train_prid)
lr_train_r2 = r2_score(y_train, y_lr_train_prid)
lr_test_mse = mean_squared_error(y_test, y_lr_test_prid)
lr_test_r2 = r2_score(y_test, y_lr_test_prid)

In [55]:
print( "lr_train_mse" ,lr_train_mse)
print( "lr_train_r2 " ,lr_train_r2 )
print( "lr_test_mse " ,lr_test_mse)
print( "lr_test_r2 " ,lr_test_r2)

lr_train_mse 779338.5591253252
lr_train_r2  0.0678641874070977
lr_test_mse  827659.5895877201
lr_test_r2  0.06325707193825962


# ***Random forest model ***

## train the model

In [68]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=2,random_state= 100)
rf.fit(x_train, y_train)
rf


RandomForestRegressor(max_depth=2, random_state=100)

#Apply the model to make pridiction

In [67]:
y_rf_train_prid =rf.predict(x_train)
y_rf_test_prid =rf.predict(x_test)

y_rf_train_prid
y_rf_test_prid

array([[-119.7625422 ,   35.37069884,   30.27133391, ..., 1371.44127264,
         530.91679145,    5.47918805],
       [-119.43699388,   35.69876611,   27.6492932 , ..., 1458.83345076,
         485.78805122,    3.16184953],
       [-119.66534648,   36.21469991,   28.03985549, ..., 1333.80840233,
         448.68971131,    2.72593066],
       ...,
       [-119.80392152,   36.76246715,   29.18156417, ..., 1183.06719524,
         385.52380409,    2.17106557],
       [-119.30366268,   35.37126006,   27.4865781 , ..., 1536.44000082,
         509.49791268,    3.46496671],
       [-119.30366268,   35.37126006,   27.4865781 , ..., 1536.44000082,
         509.49791268,    3.46496671]])

#model performance

In [64]:
from sklearn.metrics import mean_squared_error,r2_score
rf_train_mse = mean_squared_error(y_train, y_rf_train_prid)
rf_train_r2 = r2_score(y_train, y_rf_train_prid)
rf_test_mse = mean_squared_error(y_test, y_rf_test_prid)
rf_test_r2 = r2_score(y_test, y_rf_test_prid)

In [66]:
rf_result = pd.DataFrame(["Random fForest",rf_train_mse,rf_train_r2,rf_test_mse,rf_test_r2]).transpose()
rf_result.columns = ["method","training MSE", "training R2","Test MSE","Test R2"]
rf_result

method   training MSE training R2       Test MSE   Test R2
0  Random fForest  770301.139772    0.070865  818653.195019  0.065945